"""
Dictionaries to translate selections into their keywords for URL use.

Creator: Chance M.
Date: 10/18/23
"""

# URL Weapon keywords
weapon = {
  'Any'             : "any",
  'AK47'            : "ak47",
  'Awp'             : "awp",
  'Bayonet'         : "bayonet",
  'Bowie Knife'     : "survival_bowie",
  'Butterfly Knife' : "knife_butterfly",
  'Classic Knife'   : "knife_css",
  'CZ74 Auto'       : "cz75a",
  'Desert Eagle'    : "deagle",
  'Dual Barettas'   : "elite",
  'Falchion Knife'  : "knife_falchion",
  'Famas'           : "famas",
  'Five Seven'      : "fiveseven",
  'Flip Knfie'      : "knife_flip",
  'G3SG1'           : "g3sg1",
  'Galil'           : "galilar",
  'Glock-18'        : "glock",
  'Gut Knife'       : "knife_gut",
  'Huntsman Knife'  : "knife_tactical",
  'Karambit'        : "knife_karambit",
  'M249'            : "m249",
  'M4A1-S'          : "m4a1_silencer",
  'M4A1'            : "m4a1",
  'M9 Bayonet'      : "knife_m9_bayonet",
  'MAC-10'          : "mac10",
  'MAG-7'           : "mag7",
  'MP5-SD'          : "mp5sd",
  "MP7"             : "mp7",
  "MP9"             : "mp9",
  "Navaja Knife"    : "knife_gypsy_jackknife",
  "Negev"           : "negev",
  "Nomad Knife"     : "knife_outdoor",
  "Nova"            : "nova",
  "P2000"           : "hkp2000",
  "P250"            : "p250",
  "P90"             : "p90",
  "Paracord Knife"  : "knife_cord",
  "PP Bizon"        : "bizon",
  "R8 Revolver"     : "revolver",
  "Sawed Off"       : "sawedoff",
  "SCAR-20"         : "scar20",
  "SG 553"          : "sg556",
  "Shaddow Daggers" : "knife_push",
  "Skeleton Knife"  : "knife_skeleton",
  "SSG 08"          : "ssg08",
  "Stiletto Knife"  : "knife_stiletto",
  "Survival Knife"  : "knife_canis",
  "Talon Knife"     : "knife_widowmaker",
  "Tec-9"           : "tec9",
  "UMP-45"          : "ump45",
  "Ursus Knife"     : "knife_ursus",
  "USP-S"           : "usp_silencer",
  "XM1014"          : "xm1014"
}

collection = {
  "2018 Inferno Collection" : "inferno_2",
  "2018 Nuke Collection"    : "nuke_2",
  "2021 Dust Collection"    : "dust_2_2021",
  "2021 Mirage Collection"  : "mirage_2021",
  "2021 Train Colleciton"   : "train_2021",
  "2021 Vertigo Collection" : "vertigo_2021",
  "Alpha Collection"        : "bravo_ii",
  "Ancient Collection"      : "ancient",
  "Anubis Collection"       : "anubis",
  "Arms Deal Collection"    : "weapons_i",
  "Arms Deal 2 Collection"  : "weapons_ii",
  "Arms Deal 3 Collection"  : "weapons_iii",
  "Assault Collection"      : "assault",
  "Aztec Collection"        : "aztec",
  "Baggage Collection"      : "baggage",
  "Bank Collection"         : "bank",
  "Blacksite Collection"    : "blacksite",
  "Bravo Collection"        : "bravo_i",
  "Breakout Collection"     : "community_4",
  "Cache Collection"        : "cache",
  "Canals Collection"       : "canals",
  "Chop Shop Collection"    : "chopshop",
  "Chroma Collection"       : "community_6",
  "Chroma 2 Collection"     : "community_7",
  "Chroma 3 Collection"     : "community_12",
  "Clutch Collection"       : "community_19",
  "Cobblestone Collection"  : "cobblestone",
  "Control Collection"      : "control",
  "CS20 Collection"         : "community_24",
  "Danger Zone Collection"  : "community_21",
  "Dreams & Nightmares Collection": "community_30",
  "Dust Collection"         : "dust_2",
  "Dust 2 Collection"       : "dust",
  "eSports 2013 Collection" : "esports",
  "eSports 2013 Winter Collection": "esports_ii",
  "eSports 2014 Summer Collection": "esports_iii",
  "Falchion Collection"     : "community_8",
  "Fracture Collection"     : "community_26",
  "Gamma Collection"        : "community_13",
  "Gamma 2 Collection"      : "gamma_2",
  "Glove Collection"        : "community_15",
  "Gods and Monsters Collection": "gods_and_monsters",
  "Havoc Collection"        : "op10_t",
  "Horizon Collection"      : "community_20",
  "Huntsman Collection"     : "community_3",
  "Inferno Collection"      : "inferno",
  "Italy Collection"        : "italy",
  "Lake Collection"         : "lake",
  "Militia Collection"      : "militia",
  "Mirage Collection"       : "mirage",
  "Norse Collection"        : "norse",
  "Office Collection"       : "office",
  "Operation Broken Fang Collection": "community_27",
  "Operation Hydra Collection"      : "community_17",
  "Operation Riptide Collection"    : "community_29",
  "Overpass Collection"     : "overpass",
  "Phoenix Collection"      : "phoenix",
  "Prisma Collection"       : "community_25",
  "Prisma 2 Collection"     : "community_22",
  "Recoil Collection"       : "community_31",
  "Revolution Collection"   : "community_32",
  "Revolver Case Collection": "community_10",
  "Rising Sun Collection"   : "kimono",
  "Safehouse Collection"    : "safehouse",
  "Shadow Collection"       : "community_9",
  "Shattered Web Collection": "community_23",
  "Snakebite Collection"    : "community_28",
  "Spectrum Collection"     : "community_16",
  "Spectrum 2 Collection"   : "community_18",
  "St. Marc Collection"     : "stmarc",
  "Train Collection"        : "train",
  "Vanguard Collection"     : "community_5",
  "Vertigo Collection"      : "vertigo",
  "Wildfire Collection"     : "community_11",
  "Winter Offensive Collection": "community_1",
  "xray Collection"         : "xraymachine"
}
